name: Docker image build && push

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to docker registry
      run: docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD onyx.u-gakugei.ac.jp
      env:
        REGISTRY_USER: ${{ secrets.ONYX_REGISTRY_USER }}
        REGISTRY_PASSWORD: ${{ secrets.ONYX_REGISTRY_PASSWORD }}

    - name: Build docker image
      run: ./gradlew composeUp -Penvironment="production"

    - name: Push docker images
      run: |
        docker push onyx.u-gakugei.ac.jp/se00g0_app:latest # ここの名前を変更する
        docker push onyx.u-gakugei.ac.jp/se00g0_db:latest # ここの名前を変更する
    